swagger: "2.0"
info:
  title: "dp-articles-api"
  description: "Articles API for ONS Digital Publishing"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "public"
paths:
  /legacy:
    get:
      tags:
        - public
      summary: "Get a legacy bulletin"
      description: "Returns a bulletin stored in Zebedee"
      parameters:
        - $ref: '#/parameters/url'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Bulletin"
        404:
           $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

  /health:
    get:
      tags:
        - public
      summary: "Returns API's health status"
      description: "Returns health status of the API and checks on dependent services"
      produces:
        - application/json
      responses:
        200:
          description: "Successfully returns OK status with checks of dependent services"
          schema:
            $ref: "#/definitions/Health"
        429:
          description: "Services warming up or degraded (at least one check in WARNING or CRITICAL status)"
        500:
          $ref: "#/responses/InternalError"

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"
  NotFound:
    description: "URL not found"

parameters:
  url:
    name: url
    description: The url for the legacy bulletin.
    type: string
    required: true
    in: query

definitions:
  Bulletin:
    type: object
    properties:
      relatedBulletins:
        type: array
        items:
         $ref: '#/definitions/Link'
      sections:
        type: array
        items:
         $ref: '#/definitions/Section'
      accordion:
        type: array
        items:
         $ref: '#/definitions/Section'
      relatedData:
        type: array
        items:
         $ref: '#/definitions/Link'
      charts:
        type: array
        items:
         $ref: '#/definitions/Figure'
      tables:
        type: array
        items:
         $ref: '#/definitions/Figure'
      images:
        type: array
        items:
         $ref: '#/definitions/Figure'
      equations:
        type: array
        items:
         $ref: '#/definitions/Figure'
      links:
        type: array
        items:
         $ref: '#/definitions/Link'
      type:
        type: string
        example: "bulletin"
      uri:
        type: string
        example: "/economy/environmentalaccounts/bulletins/ukenvironmentalaccounts/2015-07-09"
      description:
        type: object
        properties:
          title:
            type: string
          edition:
            type: string
          summary:
            type: string
          keywords:
            type: array
            items:
              type: string
          metaDescription:
            type: string
          nationalStatistic:
            type: boolean
          latestRelease:
            type: boolean
      versions:
        type: array
        items:
          type: object
          properties:
            uri:
              type: string
            updateDate:
              type: string
            correctionNotice:
              type: string
            label:
              type: string
      alerts:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            type:
              type: string
            markdown:
              type: string
      latestReleaseUri:
        type: string
      contact:
        type: object
        properties:
          name:
            type: string
          email:
            type: string
          telephone:
            type: string
      releaseDate:
        type: string
      nextRelease:
        type: string
      datasetId:
        type: string
      unit:
        type: string
      preUnit:
        type: string
      source:
        type: string
      versionLabel:
        type: string
  Health:
    type: object
    properties:
      status:
        type: string
        description: "The status of the API"
        enum: ["OK", "WARNING", "CRITICAL"]
      version:
        type: object
        properties:
          build_time:
            type: string
            description: "The build date and time of the API"
            example: "2020-06-11T12:49:20+01:00"
          git_commit:
            type: string
            description: "The git commit hash of the API"
            example: "7c2febbf2b818175112478d4ffbadbee1b654f63"
          language:
            type: string
            description: "The programming language used to implement API"
            example: "go"
          language_version:
            type: string
            description: "The version of the programming language used to implement API"
            example: "go1.14.3"
          version:
            type: string
            description: "The version of API"
            example: "1.0.0"
      uptime:
        type: string
        description: "The uptime of API"
        example: "34516"
      start_time:
        type: string
        description: "The start date and time of API running"
        example: "2020-06-11T11:49:21.520922Z"
      checks:
        type: array
        items:
          $ref: '#/definitions/HealthChecker'
  Link:
    type: object
    properties:
      title:
        type: string
        description: "Title"
      uri:
        type: string
        description: "URI"
  Section:
    type: object
    properties:
      title:
        type: string
        description: "Title"
      markdown:
        type: string
        description: "Markdown text"
  Figure:
    type: object
    properties:
      title:
        type: string
        description: "Title"
      filename:
        type: string
        description: "File name"
      version:
        type: string
        description: "Version"
      uri:
        type: string
        description: "URI"  
  HealthChecker:
    type: object
    properties:
      name:
        type: string
        description: "The name of external service used by API"
        enum: ["mongodb"]
      status:
        type: string
        description: "The status of the external service"
        enum: ["OK", "WARNING", "CRITICAL"]
      message:
        type: string
        description: "The message status of the external service"
        example: "mongodb is OK"
      last_checked:
        type: string
        description: "The last health check date and time of the external service"
        example: "2020-06-11T11:49:50.330089Z"
      last_success:
        type: string
        description: "The last successful health check date and time of the external service"
        example: "2020-06-11T11:49:50.330089Z"
      last_failure:
        type: string
        description: "The last failed health check date and time of the external service"
        example: "2019-09-22T11:48:51.0000001Z"